export * from './footer/footer'
export * from './header/header'
export * from './headline-custom/headline-custom'
export * from './headline/headline'
export * from './customRouter/Router'
export * from './customRouterLink/Link'
export * from './loading/loading'
export * from './cloudImage/cloudImage'
export * from './lazyLoad/lazyLoad'
export * from './componentLoading/componentLoading'
export * from './timeTable/timeTable'
export * from './hoverDivAnimation/hoverDivAnimation'
export * from './defaultButton/defaultButton'
export * from './trainingClass/trainingClass'
export * from './news/news'
export * from './contactUs/contactUs'
export * from './slider/slider'
export * from './trainerInfo/trainerInfo'
export * from './trainer/trainer'
export * from './review/review'
<<<<<<< HEAD
export * from './numberSection/numberSection'
export * from './postAuthor/postAuthor'
=======
export * from './introHome/introHome'
export * from './numberSection/numberSection'
export * from './eventHour/eventHour'
>>>>>>> f6ca853a151036ad2dff95adffca42f4d7f7480a
